import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import NavBar from './components/Navbar'
import Footer from './components/Footer'




const Home: NextPage = () => {
  const [width, setWidth] = React.useState(window.innerWidth);

  React.useEffect(() => {
    window.addEventListener("resize", updateWidthAndHeight);
    return () => window.removeEventListener("resize", updateWidthAndHeight);
  });

  const updateWidthAndHeight = () => {
    setWidth(window.innerWidth);
  };

  return (
    <div>
      <Head>
        <title>Laife Fragrances</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar width={width}/>
      {width > 600?
      <div style={{ display: "flex", backgroundColor: "white", color: "black", height: "120vh", paddingTop: "100px", marginLeft: "30px", flexDirection: "row", justifyContent: "space-between" }}>
        <div>
          <p style={{ fontWeight: "bold", fontSize: "28px", marginTop: "30px" }}>Glow Your Face<br></br> & Vitality With <br></br>URBAN</p>
          <p style={{ marginTop: "10px" }}>We provide beauty and treatment services<br></br> with best quality, believe us.</p>
        </div>

        <div><img src="assets/skincare.png"></img></div>
        <div style={{ marginTop: "100px" }}><img height="20px" width="20px" src="assets/quotes.png"></img>

          <div style={{ fontSize: '14px', display: 'flex', marginRight: "100px", marginTop: "10px" }}><p>Affordable. Gorgeous and <br></br>Beauty which you deserve<br></br> of our services.</p></div>
        </div>
      </div>
      :
      <div>
          
      <div style={{marginLeft: "100px"}}><img src="assets/skincare.png"></img>
      
      </div>
      <p style={{ fontWeight: "bold", fontSize: "24px", marginTop: "30px", justifyContent: "center", alignItems: "center", marginInline:"30px",  display: "flex", textAlign: "center" }}>Glow Your Face & Vitality With URBAN</p>
      <p style={{ marginInline: "70px", marginTop: "10px", textAlign: "center" }}>We provide beauty and treatment services<br></br> with best quality, believe us.</p>
      </div>
      }

      <Footer width={width}/>


    </div>
  )
}

export default Home
